from app.knowledge.evidence.domain import EvidenceSeverity
from app.knowledge.evidence.knowledge.definitions import EvidenceDefinition
from app.knowledge.evidence.knowledge.definitions import EvidenceRule
from app.knowledge.evidence.knowledge.definitions import EvidenceRuleOperator


def m41_semantic_evidence_definitions(
) -> tuple[EvidenceDefinition, ...]:
    return (
        EvidenceDefinition(
            id="code_change_volume_signal",
            name="Code Change Volume Signal",
            category="maintainability",
            description="A code observation changed measurable source volume.",
            semantic_meaning="Code churn occurred and can support later maintenance interpretation.",
            triggering_conditions=(
                EvidenceRule(
                    id="lines-added-present",
                    measurement_id="lines_added",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=1.0,
                ),
                EvidenceRule(
                    id="files-modified-present",
                    measurement_id="files_modified",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=1.0,
                ),
            ),
            required_measurements=("lines_added", "files_modified"),
            optional_measurements=("lines_deleted", "directories_changed"),
            synthesis_rules=("all_required_measurements_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="A measurable source-code change occurred.",
            standards_references=("ISO/IEC 15939 measurement process",),
            business_interpretation="Future evidence layers may use this as source-change support.",
            known_limitations=("Does not infer risk, ownership, or expertise.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.LOW,
            rule_reliability=0.95,
        ),
        EvidenceDefinition(
            id="review_activity_signal",
            name="Review Activity Signal",
            category="developer_productivity",
            description="A code review observation contains measurable review activity.",
            semantic_meaning="Review activity happened and can support later collaboration interpretation.",
            triggering_conditions=(
                EvidenceRule(
                    id="review-count-present",
                    measurement_id="review_count",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=1.0,
                ),
            ),
            required_measurements=("review_count",),
            optional_measurements=("comment_count",),
            synthesis_rules=("required_measurement_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="A measurable review occurred.",
            standards_references=(),
            business_interpretation="Future layers may use this as collaboration evidence.",
            known_limitations=("Does not infer reviewer expertise.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.LOW,
            rule_reliability=0.9,
        ),
        EvidenceDefinition(
            id="review_latency_signal",
            name="Review Latency Signal",
            category="developer_productivity",
            description="A pull request has measurable elapsed review or merge latency.",
            semantic_meaning="Delivery flow has measurable elapsed time.",
            triggering_conditions=(
                EvidenceRule(
                    id="review-latency-present",
                    measurement_id="review_latency_seconds",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=1.0,
                ),
            ),
            required_measurements=("review_latency_seconds",),
            optional_measurements=(),
            synthesis_rules=("required_measurement_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="Review latency is measurable.",
            standards_references=(),
            business_interpretation="Future layers may use this for flow analysis.",
            known_limitations=("Does not judge whether latency is good or bad.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.INFO,
            rule_reliability=0.9,
        ),
        EvidenceDefinition(
            id="test_execution_signal",
            name="Test Execution Signal",
            category="testing",
            description="A test observation produced measurable test results.",
            semantic_meaning="Verification activity is present.",
            triggering_conditions=(
                EvidenceRule(
                    id="test-failure-count-present",
                    measurement_id="test_failures",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=0.0,
                ),
            ),
            required_measurements=("test_failures",),
            optional_measurements=(),
            synthesis_rules=("required_measurement_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="A measurable test result exists.",
            standards_references=(),
            business_interpretation="Future layers may use this for quality evidence.",
            known_limitations=("Zero failures does not prove adequate test coverage.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.LOW,
            rule_reliability=0.95,
        ),
        EvidenceDefinition(
            id="documentation_update_signal",
            name="Documentation Update Signal",
            category="documentation",
            description="A documentation observation has measurable document path structure.",
            semantic_meaning="Documentation artifact activity is present.",
            triggering_conditions=(
                EvidenceRule(
                    id="document-path-depth-present",
                    measurement_id="document_path_depth",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=1.0,
                ),
            ),
            required_measurements=("document_path_depth",),
            optional_measurements=(),
            synthesis_rules=("required_measurement_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="Documentation activity was measured.",
            standards_references=(),
            business_interpretation="Future layers may use this for knowledge-capture evidence.",
            known_limitations=("Does not assess documentation quality.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.LOW,
            rule_reliability=0.95,
        ),
        EvidenceDefinition(
            id="build_execution_signal",
            name="Build Execution Signal",
            category="infrastructure",
            description="A build observation has measurable duration.",
            semantic_meaning="Build-system activity is present.",
            triggering_conditions=(
                EvidenceRule(
                    id="build-duration-present",
                    measurement_id="build_duration_seconds",
                    operator=EvidenceRuleOperator.GTE,
                    threshold=0.0,
                ),
            ),
            required_measurements=("build_duration_seconds",),
            optional_measurements=(),
            synthesis_rules=("required_measurement_present",),
            confidence_strategy="factor_product_with_explanation",
            validation_rules=("logical", "semantic", "ontology", "dependency"),
            interpretation="Build execution was measured.",
            standards_references=(),
            business_interpretation="Future layers may use this for delivery pipeline evidence.",
            known_limitations=("Does not infer build reliability by itself.",),
            version_history=("1.0",),
            severity=EvidenceSeverity.LOW,
            rule_reliability=0.95,
        ),
    )

