import os

docs_dir = "docs/milestones"
research_dir = "research"

os.makedirs(docs_dir, exist_ok=True)
os.makedirs(research_dir, exist_ok=True)

m57_4 = """# Milestone 57.4: Repository Session & Context Resolution

## Architecture
Introduces the `RepositorySession` to encapsulate all active metadata (branch, commits, timestamps).

## Execution Diagram
`CognitiveSession` -> holds `RepositorySession` -> injected by `ContextBuilder` into `PromptContext`.

## Limitations
Requires valid GitHub tokens for live repositories; fallback relies on cached snapshots.

## Future Extensions
M60 will expand this to support multi-repository diffing by loading multiple sessions simultaneously.
"""

m57_5 = """# Milestone 57.5: Adaptive Communication

## Architecture
Decouples reasoning from presentation. `AdaptiveSynthesizer` formats verified facts using templates for `EXECUTIVE`, `ENGINEER`, `RESEARCHER`.

## Reasoning Flow
Facts generated by LLM -> Critic -> Verifier -> Synthesizer styles output.
LLM rewriting is strictly reserved for `TEACHER` and `STUDENT` modes.

## Limitations
Heuristic detection of `CommunicationMode` can occasionally misclassify nuanced conversational prompts.

## Future Extensions
Personalized style profiles stored persistently in user settings.
"""

m57_6 = """# Milestone 57.6: Benchmark Framework

## Architecture
Offline script (`benchmark_cognitive.py`) tracking 15 metrics across intent routing, planning, and verification.

## Benchmark Methodology
Executes ~30 deterministic queries covering all 4 intent classifications. Uses `MockLLMProvider` combined with deterministic outputs.
Measures Repository Resolution Accuracy by inspecting `PromptContext`.

## Limitations
Currently utilizes a stub LLM for speed and zero cost. To measure true reasoning consistency, an expensive LLM judge or human evaluation is needed.

## Future Extensions
Integration into CI/CD pipelines to block PRs that degrade intent accuracy or tool precision.
"""

m57_7 = """# Milestone 57.7: Cognitive Observability & Reflection Loop

## Architecture
Introduces `CognitiveTrace` for every stage. `ExecutionState` is now immutable.

## Policy Interactions & Reasoning Flow
Planner -> Executor -> Context -> Orchestrator -> Reflection -> `should_replan`.
If `should_replan`, loop repeats up to 3 times or until confidence stabilizes.

## Limitations
JSON trace files can grow large for long-running hybrid sessions.

## Future Extensions
Time-travel debugging UI, streaming observability graphs.
"""

research_57_4 = "# M57.4 Findings\nContext injection directly into `PromptContext` prevents polluting the user's intent string, making intent classification far more stable."
research_57_5 = "# M57.5 Findings\nHybrid synthesis (templates vs LLM) saves significant tokens and latency while providing strict fact adherence."
research_57_6 = "# M57.6 Findings\nBenchmarking revealed that intent routing heuristics require careful keyword weighting to avoid misclassifying HYBRID queries as REPOSITORY queries."
research_57_7 = "# M57.7 Findings\nImmutable state execution enables safe reflection looping without side-effect bugs, though memory usage scales linearly with loop iterations."

files = {
    f"{docs_dir}/milestone_57_4.md": m57_4,
    f"{docs_dir}/milestone_57_5.md": m57_5,
    f"{docs_dir}/milestone_57_6.md": m57_6,
    f"{docs_dir}/milestone_57_7.md": m57_7,
    f"{research_dir}/milestone_57_4_findings.md": research_57_4,
    f"{research_dir}/milestone_57_5_findings.md": research_57_5,
    f"{research_dir}/milestone_57_6_findings.md": research_57_6,
    f"{research_dir}/milestone_57_7_findings.md": research_57_7,
}

for path, content in files.items():
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

print("Documentation generated.")
