from app.intelligence.measurement.domain import ExpectedRange
from app.intelligence.measurement.domain import MeasurementDefinition
from app.intelligence.measurement.domain import MeasurementReference
from app.intelligence.measurement.domain import MeasurementUnit
from app.intelligence.measurement.domain.registry import MeasurementRegistry


class DefaultMeasurementCatalog:

    @classmethod
    def build(
        cls,
    ) -> MeasurementRegistry:
        registry = MeasurementRegistry()

        for definition in cls.definitions():
            registry.register(
                definition
            )

        return registry

    @classmethod
    def definitions(
        cls,
    ) -> list[MeasurementDefinition]:
        standards = (
            MeasurementReference(
                title="ISO/IEC 25010 software quality model",
                source="ISO/IEC",
                identifier="25010",
            ),
            MeasurementReference(
                title="Guide to the Expression of Uncertainty in Measurement",
                source="JCGM",
                identifier="GUM",
            ),
        )

        return [
            # ---------------------------------------------------------
            # Commit-level (Existing + Enhancements)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="code_churn",
                name="Code Churn",
                description="Total added and deleted lines in the observed change.",
                unit=MeasurementUnit.LOC,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("total_additions", "total_deletions"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("behavioral", "repository"),
            ),
            MeasurementDefinition(
                id="files_changed",
                name="Files Changed",
                description="Number of artifacts touched by the observed change.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="change_impact",
                category="behavioral",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("files",),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("behavioral", "structural"),
            ),
            MeasurementDefinition(
                id="patch_complexity_delta",
                name="Patch Complexity Delta",
                description="Deterministic approximation of control-flow complexity introduced.",
                unit=MeasurementUnit.COMPLEXITY,
                version="1.0",
                concept_id="complexity",
                category="structural",
                required_signals=("patch",),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("structural", "complexity"),
            ),
            MeasurementDefinition(
                id="change_distribution_entropy",
                name="Change Distribution Entropy",
                description="Entropy of line changes across touched files.",
                unit=MeasurementUnit.ENTROPY,
                version="1.0",
                minimum=0.0,
                concept_id="information_distribution",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("file_changes",),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("information", "behavioral"),
            ),
            MeasurementDefinition(
                id="change_surface_area",
                name="Change Surface Area",
                description="Deterministic size-and-spread score for the observed change.",
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=100.0,
                concept_id="change_impact",
                category="structural",
                expected_range=ExpectedRange(minimum=0.0, maximum=100.0),
                required_signals=("total_changes", "files_changed"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="weighted_mean",
                references=standards,
                tags=("impact", "behavioral"),
            ),
            MeasurementDefinition(
                id="review_attention_need",
                name="Review Attention Need",
                description="Normalized review attention score derived from churn and spread.",
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=100.0,
                concept_id="change_impact",
                category="review",
                expected_range=ExpectedRange(minimum=0.0, maximum=100.0),
                required_signals=("total_changes", "files_changed", "patch"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="weighted_mean",
                references=standards,
                tags=("impact", "review"),
            ),
            MeasurementDefinition(
                id="commit_message_length",
                name="Commit Message Length",
                description="Length of the commit message as a proxy for documentation quality.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="structural",
                category="documentation",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("message",),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("documentation", "quality"),
            ),

            # ---------------------------------------------------------
            # Per-Author Activity (Developer entity)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="author_contribution_count",
                name="Author Contribution Count",
                description="Number of commits authored.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="activity_frequency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name",),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("developer", "activity"),
            ),
            MeasurementDefinition(
                id="author_file_touch_count",
                name="Author File Touch Count",
                description="Distinct files touched by this author.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="activity_frequency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name", "files"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("developer", "spread"),
            ),
            MeasurementDefinition(
                id="author_code_churn",
                name="Author Code Churn",
                description="Total LOC changed by author.",
                unit=MeasurementUnit.LOC,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name", "total_changes"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("developer", "churn"),
            ),

            # ---------------------------------------------------------
            # Per-File Activity (Module entity)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="file_churn",
                name="File Churn",
                description="LOC changed in this file.",
                unit=MeasurementUnit.LOC,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("file_path", "changes"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("module", "churn"),
            ),
            MeasurementDefinition(
                id="file_touch_count",
                name="File Touch Count",
                description="Times this file was touched.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="activity_frequency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("file_path",),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("module", "activity"),
            ),
            MeasurementDefinition(
                id="file_addition_ratio",
                name="File Addition Ratio",
                description="Percentage of changes that are additions.",
                unit=MeasurementUnit.PERCENT,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="churn",
                category="structural",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("file_path", "additions", "changes"),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("module", "growth"),
            ),
            MeasurementDefinition(
                id="file_is_test",
                name="File Is Test",
                description="Boolean indicating if the file is a test file.",
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="structural",
                category="testing",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("file_path",),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("module", "testing"),
            ),
            MeasurementDefinition(
                id="file_is_documentation",
                name="File Is Documentation",
                description="Boolean indicating if the file is documentation.",
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="structural",
                category="documentation",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("file_path",),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("module", "documentation"),
            ),
            MeasurementDefinition(
                id="file_complexity_delta",
                name="File Complexity Delta",
                description="Control-flow complexity introduced to the file.",
                unit=MeasurementUnit.COMPLEXITY,
                version="1.0",
                concept_id="complexity",
                category="structural",
                required_signals=("file_path", "patch"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("module", "complexity"),
            ),

            # ---------------------------------------------------------
            # Per-Directory Activity (Subsystem entity)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="directory_churn",
                name="Directory Churn",
                description="Total LOC changed in directory.",
                unit=MeasurementUnit.LOC,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("directory", "changes"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("subsystem", "churn"),
            ),
            MeasurementDefinition(
                id="directory_file_count",
                name="Directory File Count",
                description="Files changed in directory.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="activity_frequency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("directory", "files"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("subsystem", "spread"),
            ),

            # ---------------------------------------------------------
            # Developer Extended Measurements (Tier 2)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="developer_knowledge_spread",
                name="Developer Knowledge Spread",
                description=(
                    "Number of distinct subsystems the developer touched in the window. "
                    "Higher = broader knowledge, lower = specialist."
                ),
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="knowledge_spread",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name", "files"),
                normalizer="identity",
                aggregation_strategy="max",
                references=standards,
                tags=("developer", "knowledge", "breadth"),
            ),
            MeasurementDefinition(
                id="developer_subsystem_focus",
                name="Developer Subsystem Focus",
                description=(
                    "Fraction of the developer's commits concentrated in their primary subsystem. "
                    "Score 1.0 = all commits in one subsystem, 0.0 = uniform spread."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="ownership_concentration",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("author_name", "files"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="mean",
                references=standards,
                tags=("developer", "knowledge", "focus"),
            ),
            MeasurementDefinition(
                id="developer_recency_score",
                name="Developer Recency Score",
                description=(
                    "Normalized recency of the developer's last contribution. "
                    "Score 1.0 = committed within last 7 days, decays exponentially."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="activity_recency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("author_name", "timestamp"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="max",
                references=standards,
                tags=("developer", "activity", "temporal"),
            ),
            MeasurementDefinition(
                id="developer_commit_frequency",
                name="Developer Commit Frequency",
                description="Total number of commits by the developer in the observation window.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="activity_frequency",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name",),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("developer", "activity"),
            ),
            MeasurementDefinition(
                id="developer_files_owned",
                name="Developer Files Owned",
                description="Number of distinct files the developer has touched (proxy for ownership surface).",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="ownership",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("author_name", "files"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("developer", "ownership"),
            ),

            # ---------------------------------------------------------
            # Subsystem Extended Measurements (Tier 2)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="subsystem_churn_rate",
                name="Subsystem Churn Rate",
                description="Total LOC changed in the subsystem per observation window.",
                unit=MeasurementUnit.LOC,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("subsystem", "changes"),
                normalizer="identity",
                aggregation_strategy="sum",
                references=standards,
                tags=("subsystem", "churn"),
            ),
            MeasurementDefinition(
                id="subsystem_contributor_count",
                name="Subsystem Contributor Count",
                description="Number of unique developers who contributed to this subsystem in the window.",
                unit=MeasurementUnit.COUNT,
                version="1.0",
                minimum=0.0,
                concept_id="ownership",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("subsystem", "author"),
                normalizer="identity",
                aggregation_strategy="max",
                references=standards,
                tags=("subsystem", "ownership", "bus_factor"),
            ),
            MeasurementDefinition(
                id="subsystem_file_concentration",
                name="Subsystem File Concentration",
                description=(
                    "Gini coefficient of file-level churn within the subsystem. "
                    "Score 1.0 = all churn in one file, 0.0 = perfectly uniform."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="ownership_concentration",
                category="structural",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("subsystem", "file_changes"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="mean",
                references=standards,
                tags=("subsystem", "concentration", "risk"),
            ),
            MeasurementDefinition(
                id="subsystem_coupling_score",
                name="Subsystem Coupling Score",
                description=(
                    "How frequently files within the subsystem change together in the same commit. "
                    "Higher = tighter internal coupling."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="coupling",
                category="structural",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("subsystem", "files"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="mean",
                references=standards,
                tags=("subsystem", "coupling", "architecture"),
            ),
            MeasurementDefinition(
                id="subsystem_volatility",
                name="Subsystem Volatility",
                description=(
                    "Standard deviation of per-commit churn within the subsystem. "
                    "High variance = unpredictable change patterns."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                concept_id="churn",
                category="temporal",
                expected_range=ExpectedRange(minimum=0.0),
                required_signals=("subsystem", "changes"),
                normalizer="identity",
                aggregation_strategy="mean",
                references=standards,
                tags=("subsystem", "volatility", "temporal"),
            ),

            # ---------------------------------------------------------
            # File Ownership (Module entity)
            # ---------------------------------------------------------
            MeasurementDefinition(
                id="file_ownership_score",
                name="File Ownership Score",
                description=(
                    "Fraction of this file's touches attributable to the majority author. "
                    "Score 1.0 = single author, 0.0 = perfectly shared."
                ),
                unit=MeasurementUnit.SCORE,
                version="1.0",
                minimum=0.0,
                maximum=1.0,
                concept_id="ownership_concentration",
                category="knowledge",
                expected_range=ExpectedRange(minimum=0.0, maximum=1.0),
                required_signals=("file_path", "author_name"),
                normalizer="bounded_score_clamp",
                aggregation_strategy="mean",
                references=standards,
                tags=("module", "ownership", "bus_factor"),
            ),
        ]
