from enum import Enum


class EntityType(Enum):
    # --- Software Engineering (original) ---
    DEVELOPER = "DEVELOPER"
    MODULE = "MODULE"
    FILE = "FILE"
    REPOSITORY = "REPOSITORY"
    PULL_REQUEST = "PULL_REQUEST"
    ISSUE = "ISSUE"
    RELEASE = "RELEASE"

    # --- Industrial: Physical Assets ---
    PLANT = "PLANT"
    FACILITY = "FACILITY"
    AREA = "AREA"
    SYSTEM = "SYSTEM"
    SUBSYSTEM = "SUBSYSTEM"
    ASSET = "ASSET"
    EQUIPMENT = "EQUIPMENT"
    COMPONENT = "COMPONENT"
    EQUIPMENT_TAG = "EQUIPMENT_TAG"
    MANUFACTURER = "MANUFACTURER"

    # --- Industrial: Personnel ---
    PERSON = "PERSON"
    ENGINEER = "ENGINEER"
    TECHNICIAN = "TECHNICIAN"
    OPERATOR = "OPERATOR"
    TEAM = "TEAM"

    # --- Industrial: Documents ---
    DOCUMENT = "DOCUMENT"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    WORK_ORDER = "WORK_ORDER"
    INCIDENT_REPORT = "INCIDENT_REPORT"
    OEM_MANUAL = "OEM_MANUAL"
    PROCEDURE = "PROCEDURE"
    SOP = "SOP"
    REGULATION = "REGULATION"

    # --- Industrial: Operational ---
    FAILURE_EVENT = "FAILURE_EVENT"
    FAILURE_MODE = "FAILURE_MODE"
    FAILURE_CAUSE = "FAILURE_CAUSE"
    MAINTENANCE_ACTION = "MAINTENANCE_ACTION"
    INSPECTION = "INSPECTION"
    RECOMMENDATION = "RECOMMENDATION"
    OPERATING_PARAMETER = "OPERATING_PARAMETER"

    # --- Industrial: Intelligence ---
    COMPLIANCE_GAP = "COMPLIANCE_GAP"
    FAILURE_PATTERN = "FAILURE_PATTERN"
    INTERVENTION = "INTERVENTION"