from enum import Enum


class EventType(Enum):
    # --- Software Engineering (original) ---
    COMMIT = "COMMIT"
    PULL_REQUEST = "PULL_REQUEST"
    REVIEW = "REVIEW"
    ISSUE = "ISSUE"
    RELEASE = "RELEASE"
    COMMENT = "COMMENT"

    # --- Industrial ---
    MAINTENANCE_ACTION = "MAINTENANCE_ACTION"
    INSPECTION = "INSPECTION"
    FAILURE_EVENT = "FAILURE_EVENT"
    INCIDENT = "INCIDENT"
    WORK_ORDER_CREATED = "WORK_ORDER_CREATED"
    WORK_ORDER_COMPLETED = "WORK_ORDER_COMPLETED"
    WORK_ORDER_DEFERRED = "WORK_ORDER_DEFERRED"
    RECOMMENDATION_ISSUED = "RECOMMENDATION_ISSUED"
    RECOMMENDATION_COMPLETED = "RECOMMENDATION_COMPLETED"
    PARAMETER_READING = "PARAMETER_READING"
    DOCUMENT_INGESTED = "DOCUMENT_INGESTED"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"
    NEAR_MISS = "NEAR_MISS"
    AUDIT_FINDING = "AUDIT_FINDING"
    QUALITY_NCR = "QUALITY_NCR"